A ritmo de Let it Be
* Opcion 1
*Verso 1: C G A F*  
Cuando entro al internet,
la propaganda del sí me invade,  
y el CNE sanciona nada.

Cuando pongo música en Spotify,  
de nuevo el sí aparece,  
y el CNE  sanciona nada.

*Coro: A G F C*
Nada, nada, de nada
El CNE sanciona nada

*Puente: A*  
Y los medios dicen que no se puede,
identificar  a estos infractores,  
y el CNE hace nada

*Verso 2:*  
Pero cuando entras a X,  
fácil los identificas,  
lees a Miño Vera y  Reinoso  
y el CNE sanciona nada.


Y si vamos a Facebook
donde Noboa paga Pauta 
La propaganda del sí me invade,
y el CNE sanciona nada

Puente:
Cuando tienes no un presidente,  
sino un dictadorzuelo  
quien se cree por encima de la ley,  
el CNE hace nada

*Verso:*
Si Nobita la ley se saltó,  
y mintió en toda su campaña,  
¿qué derechos crees que va a respetar  
si cambia la Constitución mañana?

Puente:
a noboa dile que no
dile que no que no
por la democracia, soberania y libertad
dile queno

*Cierre:*  
No seas gil, porque a ti no te llaman Gilchrist.  
Enciende tu pensamiento,  
dile que no a Noboa

el cne se parece al SRI
que cuando le pregunto como es
que dios borra impuestos
no contesta nada nada

94.6 millones volaron,  
maravilla mafiosa en el estado,  
los Noboa al mando,  
el bolsillo agrandado,  
¿y tú dices? No pasa nada…

* Opcion 2
**Verso 1:**  
Cuando navego en internet,  
la propaganda del sí me invade,  
y el CNE no dice nada de nada.  
En Spotify, al escuchar,  
la misma historia vuelve a pasar,  
y el CNE no dice nada de nada.

**Coro:**  
Nada, nada, en Ecuador no pasa nada,  
y el CNE no hace nada de nada.

**Verso 2:**  
Los medios dicen que no se puede,
descubrir quién infringe en las redes,  
y el CNE no hace nada de nada.

**Verso 3:**  
En X los puedes hallar,  
Miño, Vera y Reinoso sin dudar,  
y el CNE no dice nada de nada.  

En Facebook la pauta está,  
Noboa pagando sin parar,  
y el CNE no hace nada de nada.

**Coro:**  
Nada, nada, en Ecuador no pasa nada,  
la gente sin salud pero con vida cara.

**Verso 4:**  
Cuando en Ecuador No hay presidente,
sino una marioneta de Donald Trump,  
y el pueblo agacha la mirada,
no pasa  nada.

**Verso 5:**  
Si Nobita en campaña mintió,  
y los impuestos se los fumó,  
¿qué derechos más va a aplastar
este delincuente,  

**Coro:**  
Nada, nada, en Ecuador no pasa nada,  
Hospitales sin medicinas pero Noboa
ya no debe nada.

**Verso 6:**  
Cuando en Ecuador No hay presidente,
sino una marioneta de Donald Trump,  
y el pueblo alza la mirada,
ahí sí te dan bala.

Hermano No seas gil,
al final no te llama GilChrist
levanta tu bic y tu razón
y a Noboa dile que No.

**Coro:**
Nada, nada, en Ecuador no pasa nada,  
Los indígenas marchan y reciben bala

**Verso: 7**
El CNE es como el SRI,  
preguntas y nada va a  decir,  
cómo Dios borra los impuestos,  
de los Noboa.

**Coro:**
Nada, nada, en Ecuador no pasa nada,  
Los niños mueren en hospitales
y los Noboa saludan desde Miami.

**Verso 8:**  
A Noboa dile que no,  
por democracia, dile que no.  
Por tu libertad y dignidad,  
dile no, mil veces no.

**Coro:**
Nada, nada, en Ecuador no pasa nada,  
salen cajas de banano con droga
y la fiscalía no dice nada.

**Verso 9:**  
Millones volaron del estado,  
Noboa y mafia han gobernado,  
el bolsillo bien llenado,  
y la naturaleza a Dundee entregado

**Coro:**
Nada, nada, en Ecuador no pasa nada,  
a la naturaleza y los animales,
los derechos piensan quitarles

**Verso 10**
A Noboa dile que no,  
por democracia, dile que no.  
Por tu libertad y dignidad,  
dile no, mil veces no.

---
